### ISSUE TITLE
Authentication Fails when relogging

### ISSUE THREAD

**Issue by RyanCR03** [axieum/authme#81] opened 2023-04-15 09:28 UTC
### Expected behavior

actually authenticating when trying to log in

### Observed/actual behavior

logging in gives error "Something went wrong! Please go back and try again."
![image](https://user-images.githubusercontent.com/32957560/232205494-48c4fec6-98ce-49ba-9905-5e1f480c1bff.png)

### Steps/models to reproduce

go to multiplayer
click auth button
log out
try to log back in
error

### Version

1.19.4-6.0.0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by axieum** [comment] 2023-04-16 04:58
Hi, can you please post your game log files please :)

**Comment by RyanCR03** [comment] 2023-04-18 00:31
```
## When I log out in-game

Could not validate the Minecraft session!
com.mojang.authlib.exceptions.InvalidCredentialsException
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:122)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:106)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.joinServer(YggdrasilMinecraftSessionService.java:72)
	at me.axieum.mcmod.authme.api.util.SessionUtils.lambda$getStatus$0(SessionUtils.java:159)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

## When I try to log back in via Microsoft

Unable to acquire Xbox Live XSTS token!
java.lang.Exception: There was no access token or error description present.
	at me.axieum.mcmod.authme.api.util.MicrosoftUtils.lambda$acquireXboxXstsToken$16(MicrosoftUtils.java:412)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at me.axieum.mcmod.authme.api.util.MicrosoftUtils.lambda$acquireXboxXstsToken$17(MicrosoftUtils.java:409)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by conetopia** [comment] 2023-05-04 05:19
Confirmed last couple of versions for 1.16.5 are all also like this .
It fails after checking something about xbox.

I assumed it failed because i use an authenticator on my  account, but that was not the case, all 17 of my friends Various version of windows/web-browsers are all also having the same issue ( and they don't use authenticators ) .

**Comment by axieum** [comment] 2023-05-04 23:58
Hi @conetopia,

> I assumed it failed because i use an authenticator on my account

I also have 2FA enabled and it works for me in a fresh 1.19.4 installation (Fabric API + Auth Me).

Do you also have any logs or are they the same as https://github.com/axieum/authme/issues/81#issuecomment-1512275877? The logs shared in that comment appear to allude to Xbox returning an empty response or unaccounted for response.

> We have the mod installed on our server

This is a client-only mod, and will not do anything when installed on a server.

**Comment by axieum** [comment] 2023-07-12 10:52
Closing as unable to reproduce.

**Closed** 2023-07-12 10:52 UTC

**Comment by kevinthegreat1** [comment] 2023-07-18 05:09
Seems to be caused by [this](https://wiki.vg/Microsoft_Authentication_Scheme#:~:text=2148916238%3A%20The%20account%20is%20a%20child%20(under%2018)%20and%20cannot%20proceed%20unless%20the%20account%20is%20added%20to%20a%20Family%20by%20an%20adult.%20This%20only%20seems%20to%20occur%20when%20using%20a%20custom%20Microsoft%20Azure%20application.%20When%20using%20the%20Minecraft%20launchers%20client%20id%2C%20this%20doesn%27t%20trigger.), since this mod uses a custom Microsoft Azure client id.
